package com.agarthavision.domain.model

import java.time.Instant

/**
 * Pure-data description of one session-report PDF, produced by
 * [com.agarthavision.domain.usecase.records.ReportPdfBuilder] and consumed by
 * [com.agarthavision.domain.repository.ReportPdfRenderer].
 *
 * Carries only the DYNAMIC content of the report. Static chrome — the document title, column
 * headers, unit labels, "Generated by" — is not modeled here; the Android renderer resolves
 * those from `strings.xml` so this stays plain, JVM-testable data (per C2/C11).
 */
data class ReportPdfDocument(
    val header: ReportPdfHeader,
    val speciesRows: List<ReportPdfSpeciesRow>,
)

/**
 * The report's identity + summary numbers, rendered as the PDF's header block.
 */
data class ReportPdfHeader(
    val reportId: String,
    val sessionId: String,
    val sessionLabel: String?,
    /** Supabase user id of the medtech who generated the report. */
    val generatedBy: String,
    val generatedAt: Instant,
    val deviceId: String,
    val totalSamples: Int,
    val totalEggsConfirmed: Int,
    /** Canonical species names (per [EggSpecies.canonicalClass]) with at least one confirmed egg. */
    val positiveSpecies: List<String>,
)

/**
 * One row of the per-species findings table.
 *
 * [epg] is EPG (eggs per gram; count × [com.agarthavision.core.util.EpgCalculator.MULTIPLIER]),
 * NOT a density measurement. This is a temporary stand-in metric — ticket 86d4a6jxw replaces it
 * with LPF (Low Power Field) density once that pipeline lands. Do not treat this column as
 * final; every renderer of this row must label it "EPG" until that ticket lands.
 */
data class ReportPdfSpeciesRow(
    val speciesDisplayName: String,
    val epg: Int,
)
