package com.agarthavision.domain.model

import java.time.Instant

/**
 * Pure-data description of one session-report PDF, produced by
 * [com.agarthavision.domain.usecase.records.ReportPdfBuilder] and consumed by
 * [com.agarthavision.domain.repository.ReportPdfRenderer].
 *
 * Carries only the DYNAMIC content of the report. Static chrome — the document title, column
 * headers, unit labels, "Generated by" — is not modeled here; the Android renderer resolves
 * those from `strings.xml` so this stays plain, JVM-testable data (per C2/C11).
 */
data class ReportPdfDocument(
    val header: ReportPdfHeader,
    val speciesRows: List<ReportPdfSpeciesRow>,
)

/**
 * The report's identity + summary numbers, rendered as the PDF's header block.
 */
data class ReportPdfHeader(
    val reportId: String,
    val sessionId: String,
    val sessionLabel: String?,
    /** Supabase user id of the medtech who generated the report. */
    val generatedBy: String,
    val generatedAt: Instant,
    val deviceId: String,
    val totalSamples: Int,
    val totalEggsConfirmed: Int,
    /** Canonical species names (per [EggSpecies.canonicalClass]) with at least one confirmed egg. */
    val positiveSpecies: List<String>,
)

/**
 * One row of the per-species findings table.
 *
 * Density is reported per Low Power Field (LPF), calculated as the mean egg count across all 
 * fields examined in a session, as the observed range (min-max).
 *
 * The mean went with PB-17: the session figure is a range, and a mean averages a single heavy
 * field away under nine clean ones - which is the field a medtech most needs to see.
 */
data class ReportPdfSpeciesRow(
    val speciesDisplayName: String,
    val min: Int,
    val max: Int,
    /**
     * The qualitative reading for the worst field, or null when the species was never seen.
     *
     * Carried rather than recomputed in the renderer, so the page and the screen cannot end up
     * describing the same range differently.
     */
    val descriptor: LpfDescriptor? = null,
)
