package com.agarthavision.data.local.psgc

import com.agarthavision.data.local.entity.PsgcBarangayEntity
import java.io.Reader

/**
 * Parses the bundled PSGC asset into Room rows.
 *
 * Pure Kotlin over a [Reader] so it is unit-testable on the JVM with no device, no Room and
 * no asset manager. Strict by design — a malformed row throws rather than seeding a
 * half-populated picker entry, which would surface as a barangay with no city.
 *
 * The asset is RFC 4180 CSV: 133 barangay names contain commas, so quoted fields are real.
 * Generated by `tools/psgc/build-psgc-asset.py`; the column order below is that file's
 * header.
 */
object PsgcCsvParser {
    private const val COLUMNS = 9

    private const val CODE = 0
    private const val NAME = 1
    private const val CITY_MUNI_CODE = 2
    private const val CITY_MUNI_NAME = 3
    private const val PROVINCE_CODE = 4
    private const val PROVINCE_NAME = 5
    private const val REGION_CODE = 6
    private const val REGION_NAME = 7
    private const val SEARCH_EXTRA = 8

    /**
     * Reads every data row, skipping the header. Returns rows in file order.
     *
     * Materialises the whole file, so prefer [parseLines] when seeding — 42,010 rows held
     * at once is a needless allocation spike on a low-end device.
     *
     * @throws IllegalArgumentException on a row with the wrong column count or a blank
     *   required field.
     */
    fun parse(reader: Reader): List<PsgcBarangayEntity> =
        reader.buffered().useLines { parseLines(it).toList() }

    /**
     * Lazily maps asset lines to rows, skipping the header, so a caller can insert in
     * chunks without ever holding the full dataset.
     *
     * @throws IllegalArgumentException on a row with the wrong column count or a blank
     *   required field.
     */
    fun parseLines(lines: Sequence<String>): Sequence<PsgcBarangayEntity> =
        lines
            .withIndex()
            .drop(1)
            .filter { (_, line) -> line.isNotBlank() }
            .map { (index, line) -> toEntity(splitCsvLine(line), line = index + 1) }

    private fun toEntity(fields: List<String>, line: Int): PsgcBarangayEntity {
        require(fields.size == COLUMNS) {
            "PSGC line $line has ${fields.size} fields, expected $COLUMNS"
        }
        val code = fields[CODE]
        val name = fields[NAME]
        val cityMuniName = fields[CITY_MUNI_NAME]
        val regionName = fields[REGION_NAME]
        require(code.isNotBlank() && name.isNotBlank()) { "PSGC line $line has no code or name" }
        require(cityMuniName.isNotBlank() && regionName.isNotBlank()) {
            "PSGC barangay $code has no city/municipality or region"
        }

        val provinceName = fields[PROVINCE_NAME].ifBlank { null }
        return PsgcBarangayEntity(
            code = code,
            name = name,
            cityMuniCode = fields[CITY_MUNI_CODE],
            cityMuniName = cityMuniName,
            // Blank rather than absent for chartered cities — see PsgcBarangayEntity.
            provinceCode = fields[PROVINCE_CODE].ifBlank { null },
            provinceName = provinceName,
            regionCode = fields[REGION_CODE],
            regionName = regionName,
            searchText = searchTextOf(
                name = name,
                cityMuniName = cityMuniName,
                provinceName = provinceName,
                searchExtra = fields[SEARCH_EXTRA],
            ),
        )
    }

    /**
     * Builds the search haystack. Lowercased here, in Kotlin, because SQLite's `lower()`
     * folds ASCII only and 438 barangay names carry characters outside ASCII, including `ñ`.
     */
    private fun searchTextOf(
        name: String,
        cityMuniName: String,
        provinceName: String?,
        searchExtra: String,
    ): String =
        listOf(name, cityMuniName, provinceName.orEmpty(), searchExtra)
            .filter { it.isNotBlank() }
            .joinToString(separator = " ")
            .lowercase()

    /** Splits one CSV line, honouring `"`-quoted fields and doubled escaped quotes. */
    private fun splitCsvLine(line: String): List<String> {
        val fields = mutableListOf<String>()
        val field = StringBuilder()
        var quoted = false
        var index = 0
        while (index < line.length) {
            val char = line[index]
            when {
                quoted && char == '"' && line.getOrNull(index + 1) == '"' -> {
                    field.append('"')
                    index += 1
                }
                char == '"' -> quoted = !quoted
                char == ',' && !quoted -> {
                    fields += field.toString()
                    field.setLength(0)
                }
                else -> field.append(char)
            }
            index += 1
        }
        fields += field.toString()
        return fields
    }
}
